import type { ProfessionalExercise } from '../types';

export const DEFAULT_PROFESSIONAL_EXERCISES: ProfessionalExercise[] = [
  {
    id: 'barbell-bench-press',
    name: 'Barbell Bench Press',
    arabicName: 'دفع بار على المقعد',
    category: 'Strength',
    muscleGroup: 'Chest',
    secondaryMuscles: ['Triceps', 'Anterior Deltoid'],
    equipment: 'Barbell, Bench',
    difficulty: 'intermediate',
    movementPattern: 'horizontal push',
    unilateral: false,
    primaryAxis: 'push',
    exerciseType: 'compound',
    instructions: 'Lie flat on the bench, retract shoulder blades, press bar from chest to full lockout under control.',
    coachingCues: ['Pinch the shoulder blades', 'Drive through the heels', 'Keep wrists neutral'],
    commonMistakes: ['Flared elbows', 'Bouncing the bar off chest', 'Poor scapular control'],
    safetyTips: ['Use a spotter for heavy sets', 'Maintain a neutral spine'],
    regressionExercises: ['dumbbell-bench-press', 'push-ups'],
    progressionExercises: ['pause-bench-press', 'close-grip-bench-press'],
    replacementExercises: ['incline-dumbbell-press', 'push-ups'],
    imageUrl: '',
    videoUrl: '',
    tags: ['strength','powerlifting','chest']
  },
  {
    id: 'back-squat',
    name: 'Back Squat',
    arabicName: 'قرفصاء بار خلفي',
    category: 'Strength',
    muscleGroup: 'Legs',
    secondaryMuscles: ['Glutes', 'Hamstrings', 'Core'],
    equipment: 'Barbell, Rack',
    difficulty: 'advanced',
    movementPattern: 'squat',
    unilateral: false,
    primaryAxis: 'legs',
    exerciseType: 'compound',
    instructions: 'Stand under bar, brace core, sit hips back and descend until thighs are parallel or below, drive through heels to stand.',
    coachingCues: ['Spread the floor with your feet', 'Brace before you descend', 'Keep chest up'],
    commonMistakes: ['Knees caving in', 'Rounding the lower back', 'Shallow depth'],
    safetyTips: ['Use safety pins in rack for heavy work', 'Warm up hips and ankles'],
    regressionExercises: ['goblet-squat','box-squat'],
    progressionExercises: ['pause-squat','tempo-squat'],
    replacementExercises: ['front-squat','leg-press'],
    imageUrl: '',
    videoUrl: '',
    tags: ['strength','powerlifting','legs']
  },
  {
    id: 'clean-and-jerk',
    name: 'Clean & Jerk',
    arabicName: 'الكلين وجرك',
    category: 'Olympic Lifting',
    muscleGroup: 'Full Body',
    secondaryMuscles: ['Quadriceps','Hamstrings','Upper Back','Shoulders'],
    equipment: 'Barbell',
    difficulty: 'advanced',
    movementPattern: 'explosive triple extension',
    unilateral: false,
    primaryAxis: 'full body',
    exerciseType: 'olympic',
    instructions: 'Pull the bar with a powerful hip extension, receive in a front squat, then drive overhead with legs and arms to finish the jerk.',
    coachingCues: ['Fast hips','Keep the bar close','Aggressive receiving position'],
    commonMistakes: ['Early arm bend','Late second pull','Poor receiving mobility'],
    safetyTips: ['Train with light technical sets first','Use bumper plates on platform'],
    regressionExercises: ['hang-power-clean','push-press'],
    progressionExercises: ['split-jerk','full-clean'],
    replacementExercises: ['power-clean','clean-pull'],
    imageUrl: '',
    videoUrl: '',
    tags: ['olympic','power','explosive']
  },
  {
    id: 'kettlebell-swing',
    name: 'Kettlebell Swing',
    arabicName: 'تلويح كيتل بيل',
    category: 'Functional Training',
    muscleGroup: 'Posterior Chain',
    secondaryMuscles: ['Hamstrings','Glutes','Core'],
    equipment: 'Kettlebell',
    difficulty: 'intermediate',
    movementPattern: 'hip hinge',
    unilateral: false,
    primaryAxis: 'full body',
    exerciseType: 'power',
    instructions: 'Hinge at hips, swing the kettlebell to eye level using a powerful hip snap, keep arms relaxed.',
    coachingCues: ['Snap the hips','Keep a soft knee','Tight core'],
    commonMistakes: ['Squatting instead of hinging','Using arms to lift the bell'],
    safetyTips: ['Use appropriate weight','train in an open area'],
    regressionExercises: ['romanian-deadlift','hip-hinge-drill'],
    progressionExercises: ['single-arm-swing','kettlebell-high-swing'],
    replacementExercises: ['deadlift','power-clean'],
    imageUrl: '',
    videoUrl: '',
    tags: ['functional','power','conditioning']
  },
  {
    id: 'pull-up',
    name: 'Pull-Up',
    arabicName: 'سحب الجسم للأعلى',
    category: 'Calisthenics',
    muscleGroup: 'Back',
    secondaryMuscles: ['Biceps','Rear Delts','Core'],
    equipment: 'Pull-Up Bar',
    difficulty: 'advanced',
    movementPattern: 'vertical pull',
    unilateral: false,
    primaryAxis: 'pull',
    exerciseType: 'bodyweight',
    instructions: 'Hang from bar, retract scapula, pull chin over bar with a controlled eccentric.',
    coachingCues: ['Lead with chest','Use scapular control','Avoid kipping unless intended'],
    commonMistakes: ['Shrugging shoulders','Using momentum unintentionally'],
    safetyTips: ['Warm up shoulders','avoid swinging with back pain'],
    regressionExercises: ['band-assisted-pullup','lat-pulldown'],
    progressionExercises: ['weighted-pullup','one-arm-pullup-progressions'],
    replacementExercises: ['inverted-row','lat-pulldown'],
    imageUrl: '',
    videoUrl: '',
    tags: ['bodyweight','pull','back']
  },
  {
    id: 'hip-flexor-stretch',
    name: 'Hip Flexor Stretch',
    arabicName: 'تمدد مُثَنّي الورك',
    category: 'Mobility',
    muscleGroup: 'Hip Flexors',
    secondaryMuscles: ['Quads','Psoas'],
    equipment: 'None',
    difficulty: 'beginner',
    movementPattern: 'stretch',
    unilateral: true,
    primaryAxis: 'legs',
    exerciseType: 'mobility',
    instructions: 'Kneel on one knee, push hips forward until a stretch is felt in the front of the hip, hold and breathe.',
    coachingCues: ['Tuck the pelvis','keep torso upright','breathe into the stretch'],
    commonMistakes: ['Overarching the low back','Leaning forward from the torso'],
    safetyTips: ['Avoid forcing into pain','maintain neutral spine'],
    regressionExercises: ['standing-hip-flexor-stretch'],
    progressionExercises: ['loaded-lunge-stretch'],
    replacementExercises: ['pigeon-pose'],
    imageUrl: '',
    videoUrl: '',
    tags: ['mobility','rehab']
  },
  {
    id: 'row-machine',
    name: 'Rowing Machine (500m sprint)',
    arabicName: 'جهاز التجذيف (سباق 500م)',
    category: 'Cardio',
    muscleGroup: 'Full Body',
    secondaryMuscles: ['Back','Legs','Core'],
    equipment: 'Rowing Machine',
    difficulty: 'intermediate',
    movementPattern: 'cardio',
    unilateral: false,
    primaryAxis: 'full body',
    exerciseType: 'cardio',
    instructions: 'Drive with legs, hinge at hips, finish with a strong pull to the chest, maintain cadence for distance.',
    coachingCues: ['Explode with legs','Maintain smooth rhythm','Control recovery'],
    commonMistakes: ['Arm-first rowing','Collapsing upper back'],
    safetyTips: ['Set damper appropriately','avoid overgripping'],
    regressionExercises: ['assault-bike-intervals','steady-state-row'],
    progressionExercises: ['longer-sprints','increased-intensity-intervals'],
    replacementExercises: ['bike-sprint','treadmill-sprint'],
    imageUrl: '',
    videoUrl: '',
    tags: ['cardio','hiit']
  }
];

export default DEFAULT_PROFESSIONAL_EXERCISES;
