import React, { useState, useEffect, useRef } from 'react';
import { db } from '../firebase';
import { collection, addDoc, query, orderBy, onSnapshot, serverTimestamp } from 'firebase/firestore';
import { Send, User, ShieldCheck, Mic, Square, Loader2, Sparkles, FileAudio, Bot, Volume2, VolumeX, ChevronDown } from 'lucide-react';
import { aiMasterEngine } from '../services/aiMasterEngine';
import type { UserProfile } from '../types';
import { motion, AnimatePresence } from 'motion/react';
import { logClientActivity } from '../lib/activityLog';
import { useI18n } from '../lib/i18n';

interface Message {
  id: string;
  text: string;
  senderId: string;
  receiverId: string;
  timestamp: any;
  voiceSummary?: string;
  audioBase64?: string;
  audioMime?: string;
  /** true = message was generated by the AI bot (not by a human) */
  isAI?: boolean;
}

interface ChatProps {
  currentUserId: string;
  currentUserName?: string;
  targetUserId: string;
  targetUserName: string;
  isCoach?: boolean;
  currentUserProfile?: UserProfile;
}

type MicMode = 'text' | 'note' | 'ai';

/** Sentinel UID used by the AI auto-reply bot inside the chat collection. */
const AI_BOT_SENDER_ID = 'ai-coach-bot';

export default function Chat({ currentUserId, currentUserName, targetUserId, targetUserName, isCoach = false, currentUserProfile }: ChatProps) {
  const { locale } = useI18n();
  const [messages, setMessages] = useState<Message[]>([]);
  const [newMessage, setNewMessage] = useState('');
  const [recording, setRecording] = useState(false);
  const [transcribing, setTranscribing] = useState(false);
  const [voiceError, setVoiceError] = useState<string>('');
  const [pendingSummary, setPendingSummary] = useState<string>('');
  const [pendingAudio, setPendingAudio] = useState<{ dataUrl: string; mime: string } | null>(null);
  const [micMode, setMicMode] = useState<MicMode>('text');
  const [micMenuOpen, setMicMenuOpen] = useState(false);
  const [aiReply, setAiReply] = useState<string>('');
  const [aiThinking, setAiThinking] = useState(false);
  const [autoAiThinking, setAutoAiThinking] = useState(false);
  const [ttsOn, setTtsOn] = useState<boolean>(() => {
    try { return localStorage.getItem('coachpro:tts') === '1'; } catch { return false; }
  });
  const [speaking, setSpeaking] = useState(false);
  /** Whether the human coach has replied at least once — used to suppress AI
   *  auto-replies once the captain is actively in the conversation. */
  const coachHasReplied = useRef(false);

  const scrollRef = useRef<HTMLDivElement>(null);
  const recorderRef = useRef<MediaRecorder | null>(null);
  const chunksRef = useRef<Blob[]>([]);

  const chatId = [currentUserId, targetUserId].sort().join('_');

  useEffect(() => {
    const q = query(
      collection(db, 'chats', chatId, 'messages'),
      orderBy('timestamp', 'asc')
    );

    const unsubscribe = onSnapshot(q, (snapshot) => {
      const msgs = snapshot.docs.map(doc => ({
        id: doc.id,
        ...doc.data()
      })) as Message[];
      setMessages(msgs);

      // Track whether the human coach (not AI bot) has ever replied.
      if (msgs.some(m => m.senderId === targetUserId && !m.isAI)) {
        coachHasReplied.current = true;
      }

      setTimeout(() => {
        scrollRef.current?.scrollIntoView({ behavior: 'smooth' });
      }, 100);
    }, (error) => {
      console.error("Chat listener error:", error);
    });

    return () => unsubscribe();
  }, [chatId, targetUserId]);

  /**
   * Sends an AI auto-reply as a bot message visible to both the client and
   * the coach. The reply is only triggered when the client (non-coach) sends a
   * plain text message AND the human coach has not yet replied recently.
   */
  const triggerAIAutoReply = async (userMessage: string) => {
    if (!currentUserProfile || isCoach) return;
    // Don't auto-reply if the coach is actively in the conversation.
    if (coachHasReplied.current) return;

    setAutoAiThinking(true);
    try {
      const reply = await aiMasterEngine.getQuickReply(userMessage, currentUserProfile, locale);
      await addDoc(collection(db, 'chats', chatId, 'messages'), {
        text: reply,
        senderId: AI_BOT_SENDER_ID,
        receiverId: currentUserId,
        timestamp: serverTimestamp(),
        isAI: true,
      });
      if (ttsOn) speakText(reply);
    } catch (err) {
      console.warn('[Chat] AI auto-reply failed:', err);
    } finally {
      setAutoAiThinking(false);
    }
  };

  const handleSendMessage = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!newMessage.trim()) return;

    const textToSend = newMessage;
    const summaryToSend = pendingSummary;
    const audioToSend = pendingAudio;
    setNewMessage('');
    setPendingSummary('');
    setPendingAudio(null);

    try {
      await addDoc(collection(db, 'chats', chatId, 'messages'), {
        text: textToSend,
        senderId: currentUserId,
        receiverId: targetUserId,
        timestamp: serverTimestamp(),
        ...(summaryToSend ? { voiceSummary: summaryToSend } : {}),
        ...(audioToSend ? { audioBase64: audioToSend.dataUrl, audioMime: audioToSend.mime } : {}),
      });

      if (!isCoach) {
        await logClientActivity(
          currentUserId,
          currentUserName || 'Client',
          summaryToSend ? 'voice_note_uploaded' : 'chat_sent',
          summaryToSend ? 'أرسل رسالة صوتية للكوتش' : 'أرسل رسالة للكوتش',
          summaryToSend ? { hasVoiceSummary: true } : {},
        );
        // Fire AI auto-reply (non-blocking) — don't await so the UX stays fast.
        triggerAIAutoReply(textToSend);
      }
    } catch (error) {
      console.error("Error sending message:", error);
    }
  };

  const startRecording = async () => {
    setVoiceError('');
    if (typeof window === 'undefined' || !navigator.mediaDevices?.getUserMedia) {
      setVoiceError(locale === 'en' ? 'Your browser does not support voice recording.' : 'متصفحك لا يدعم تسجيل الصوت.');
      return;
    }
    try {
      const stream = await navigator.mediaDevices.getUserMedia({ audio: true, video: false });
      // Pick the best supported MIME — Android Chrome prefers audio/webm but some
      // WebViews (Capacitor) only support audio/mp4 or audio/ogg.
      const mimePreferences = [
        'audio/webm;codecs=opus',
        'audio/webm',
        'audio/mp4',
        'audio/ogg;codecs=opus',
        'audio/ogg',
      ];
      const mime = mimePreferences.find(m => MediaRecorder.isTypeSupported(m)) || '';
      const rec = mime ? new MediaRecorder(stream, { mimeType: mime }) : new MediaRecorder(stream);
      chunksRef.current = [];
      rec.ondataavailable = (ev) => { if (ev.data.size > 0) chunksRef.current.push(ev.data); };
      rec.onstop = async () => {
        try {
          stream.getTracks().forEach(t => t.stop());
          const finalMime = rec.mimeType || mime || 'audio/webm';
          const blob = new Blob(chunksRef.current, { type: finalMime });
          await transcribeBlob(blob, finalMime);
        } catch (err: any) {
          setVoiceError(err?.message || (locale === 'en' ? 'Voice recording failed' : 'فشل تسجيل الصوت'));
        } finally {
          setRecording(false);
        }
      };
      rec.start(1000); // collect in 1-second chunks so data doesn't get lost on crash
      recorderRef.current = rec;
      setRecording(true);
    } catch (err: any) {
      const msg = err?.name === 'NotAllowedError'
        ? (locale === 'en' ? 'Microphone permission denied. Please allow microphone access in your browser settings.' : 'تم رفض إذن الميكروفون. يرجى السماح بالوصول للميكروفون من إعدادات المتصفح.')
        : (err?.message || (locale === 'en' ? 'Could not access microphone.' : 'تعذّر الوصول للميكروفون.'));
      setVoiceError(msg);
      setRecording(false);
    }
  };

  const stopRecording = () => {
    try { recorderRef.current?.stop(); } catch {}
  };

  const transcribeBlob = async (blob: Blob, mimeType: string) => {
    setTranscribing(true);
    try {
      const reader = new FileReader();
      const dataUrl: string = await new Promise((resolve, reject) => {
        reader.onloadend = () => resolve(reader.result as string);
        reader.onerror = () => reject(reader.error);
        reader.readAsDataURL(blob);
      });
      const base = (import.meta as any).env?.BASE_URL || '/';
      const res = await fetch(`${base}api/transcribe`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          audioBase64: dataUrl,
          mimeType,
          language: locale === 'en' ? 'en' : 'ar',
          summarize: isCoach,
        }),
      });
      if (!res.ok) {
        const err = await res.json().catch(() => ({}));
        throw new Error(err.error || `HTTP ${res.status}`);
      }
      const { transcript, summary } = await res.json();

      if (micMode === 'ai') {
        if (!transcript) {
          setVoiceError(locale === 'en' ? 'Voice not recognized — please try again.' : 'لم يتم التعرف على الصوت — حاول مرة أخرى.');
          return;
        }
        setAiThinking(true);
        try {
          const reply = currentUserProfile
            ? await aiMasterEngine.getQuickReply(transcript, currentUserProfile, locale)
            : (locale === 'en' ? 'Cannot reply without client profile — please reopen the chat.' : 'لا يمكن الرد بدون ملف العميل — يرجى إعادة فتح المحادثة.');
          setAiReply(`❓ ${transcript}\n\n💬 ${reply}`);
          if (ttsOn) speakText(reply);
        } finally {
          setAiThinking(false);
        }
      } else if (micMode === 'note') {
        if (transcript) setNewMessage((prev) => (prev ? `${prev} ${transcript}` : transcript));
        if (summary) setPendingSummary(summary);
        if (blob.size < 700 * 1024) {
          setPendingAudio({ dataUrl, mime: mimeType });
        }
      } else {
        if (transcript) setNewMessage((prev) => (prev ? `${prev} ${transcript}` : transcript));
        if (summary) setPendingSummary(summary);
      }
    } catch (err: any) {
      console.error('[Chat] transcribe failed:', err);
      setVoiceError(locale === 'en' ? `Transcription failed: ${err?.message || 'Unknown error'}` : `فشل التفريغ: ${err?.message || 'خطأ غير معروف'}`);
    } finally {
      setTranscribing(false);
    }
  };

  const startWithMode = async (mode: MicMode) => {
    setMicMode(mode);
    setMicMenuOpen(false);
    setAiReply('');
    await startRecording();
  };

  const speakText = (text: string) => {
    if (typeof window === 'undefined' || !window.speechSynthesis) return;
    try {
      window.speechSynthesis.cancel();
      const utter = new SpeechSynthesisUtterance(text);
      const isArabic = /[\u0600-\u06FF]/.test(text);
      utter.lang = isArabic ? 'ar-EG' : 'en-US';
      utter.rate = 1;
      utter.pitch = 1;
      const pickVoice = () => {
        const voices = window.speechSynthesis.getVoices();
        if (!voices.length) return;
        const match = voices.find(v => v.lang.toLowerCase().startsWith(isArabic ? 'ar' : 'en'));
        if (match) utter.voice = match;
        utter.onstart = () => setSpeaking(true);
        utter.onend = () => setSpeaking(false);
        utter.onerror = () => setSpeaking(false);
        window.speechSynthesis.speak(utter);
      };
      const voices = window.speechSynthesis.getVoices();
      if (voices.length) { pickVoice(); }
      else {
        const onVoices = () => { pickVoice(); window.speechSynthesis.removeEventListener('voiceschanged', onVoices); };
        window.speechSynthesis.addEventListener('voiceschanged', onVoices);
      }
    } catch (e) { console.warn('[Chat] TTS failed:', e); }
  };

  const stopSpeaking = () => {
    try { window.speechSynthesis?.cancel(); } catch {}
    setSpeaking(false);
  };

  const toggleTts = () => {
    setTtsOn((v) => {
      const next = !v;
      try { localStorage.setItem('coachpro:tts', next ? '1' : '0'); } catch {}
      if (!next) stopSpeaking();
      return next;
    });
  };

  const isOwnMessage = (msg: Message) => msg.senderId === currentUserId;
  const isAIMessage = (msg: Message) => msg.senderId === AI_BOT_SENDER_ID || msg.isAI;

  return (
    <div className="flex flex-col h-[500px] bg-slate-900/50 border border-white/5 rounded-[2rem] overflow-hidden">
      {/* Header */}
      <div className="p-4 bg-slate-800/50 border-b border-white/5 flex items-center justify-between">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-full bg-blue-600/20 flex items-center justify-center border border-blue-500/20">
            {isCoach ? <User className="text-blue-400" size={20} /> : <ShieldCheck className="text-blue-400" size={20} />}
          </div>
          <div>
            <h4 className="text-sm font-bold text-white">{targetUserName}</h4>
            <p className="text-[10px] text-green-500 font-bold uppercase">{locale === 'en' ? 'Online' : 'متصل الآن'}</p>
          </div>
        </div>
        <div className="flex items-center gap-2">
          {!isCoach && currentUserProfile && (
            <div className="flex items-center gap-1 px-2 py-1 rounded-lg bg-violet-600/10 border border-violet-500/20">
              <Bot size={11} className="text-violet-400" />
              <span className="text-[10px] text-violet-300 font-bold">
                {locale === 'en' ? 'AI First Layer' : 'AI الطبقة الأولى'}
              </span>
            </div>
          )}
          <button
            type="button"
            onClick={toggleTts}
            title={ttsOn ? (locale === 'en' ? 'Mute AI voice' : 'إيقاف صوت الذكاء') : (locale === 'en' ? 'Enable AI voice' : 'تفعيل صوت الذكاء')}
            className={`p-2 rounded-xl border transition-all flex items-center gap-1.5 text-[10px] font-bold ${
              ttsOn
                ? 'bg-violet-600/20 border-violet-500/40 text-violet-200'
                : 'bg-slate-800/50 border-white/5 text-slate-400 hover:text-slate-200'
            }`}
          >
            {ttsOn ? <Volume2 size={14} /> : <VolumeX size={14} />}
            <span className="hidden sm:inline">{ttsOn ? 'AI Voice ON' : 'AI Voice OFF'}</span>
          </button>
        </div>
      </div>

      {/* Messages */}
      <div className="flex-1 overflow-y-auto p-4 space-y-3 custom-scrollbar">
        {messages.map((msg) => {
          const own = isOwnMessage(msg);
          const aiMsg = isAIMessage(msg);

          if (aiMsg) {
            return (
              <div key={msg.id} className="flex justify-end">
                <div className="max-w-[85%] rounded-2xl rounded-br-none bg-violet-900/40 border border-violet-500/20 p-3 text-sm text-violet-100 shadow-lg">
                  <div className="flex items-center gap-1.5 mb-1.5">
                    <Bot size={12} className="text-violet-400" />
                    <span className="text-[10px] font-black uppercase tracking-wider text-violet-400">
                      {locale === 'en' ? 'Coach Pro AI' : 'كوتش برو AI'}
                    </span>
                  </div>
                  <p className="whitespace-pre-wrap leading-relaxed">{msg.text}</p>
                  {msg.timestamp && (
                    <p className="text-[8px] mt-1 opacity-40 text-violet-200">
                      {new Date(msg.timestamp?.toDate?.() ?? msg.timestamp).toLocaleTimeString(
                        locale === 'ar' ? 'ar-EG' : 'en-US',
                        { hour: '2-digit', minute: '2-digit' }
                      )}
                    </p>
                  )}
                </div>
              </div>
            );
          }

          return (
            <div
              key={msg.id}
              className={`flex ${own ? 'justify-start' : 'justify-end'}`}
            >
              <div className={`max-w-[80%] p-3 rounded-2xl text-sm ${
                own
                  ? 'bg-blue-600 text-white rounded-tr-none shadow-lg shadow-blue-600/10'
                  : 'bg-slate-800 text-slate-300 rounded-tl-none border border-white/5'
              }`}>
                <p className="whitespace-pre-wrap leading-relaxed">{msg.text}</p>
                {msg.audioBase64 && (
                  <audio controls src={msg.audioBase64} className="mt-2 w-full max-w-[260px] h-8 rounded-lg" />
                )}
                {msg.voiceSummary && (
                  <div className="mt-2 pt-2 border-t border-white/10 text-[11px] opacity-90 font-sans">
                    <p className="flex items-center gap-1 font-bold uppercase tracking-wider mb-1">
                      <Sparkles size={10} /> {locale === 'en' ? 'Smart Summary' : 'ملخص ذكي'}
                    </p>
                    <p className="whitespace-pre-wrap">{msg.voiceSummary}</p>
                  </div>
                )}
                {msg.timestamp && (
                  <p className={`text-[8px] mt-1 opacity-50 ${own ? 'text-blue-100' : 'text-slate-500'}`}>
                    {new Date(msg.timestamp?.toDate?.() ?? msg.timestamp).toLocaleTimeString(
                      locale === 'ar' ? 'ar-EG' : 'en-US',
                      { hour: '2-digit', minute: '2-digit' }
                    )}
                  </p>
                )}
              </div>
            </div>
          );
        })}

        {/* AI auto-reply typing indicator */}
        <AnimatePresence>
          {autoAiThinking && (
            <motion.div
              initial={{ opacity: 0, y: 6 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: 6 }}
              className="flex justify-end"
            >
              <div className="px-4 py-2.5 rounded-2xl rounded-br-none bg-violet-900/40 border border-violet-500/20 flex items-center gap-2">
                <Bot size={12} className="text-violet-400" />
                <span className="text-[11px] text-violet-300 font-bold">
                  {locale === 'en' ? 'AI Coach thinking...' : 'الكوتش الذكي يفكر...'}
                </span>
                <Loader2 size={12} className="animate-spin text-violet-400" />
              </div>
            </motion.div>
          )}
        </AnimatePresence>

        <div ref={scrollRef} />
      </div>

      {/* Voice status banner */}
      <AnimatePresence>
        {(transcribing || voiceError || pendingSummary || aiThinking || aiReply) && (
          <motion.div
            initial={{ opacity: 0, y: 8 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: 8 }}
            className={`px-4 py-2 text-[11px] border-t flex items-start gap-2 ${
              voiceError
                ? 'bg-red-500/10 border-red-500/20 text-red-300'
                : aiReply
                ? 'bg-violet-500/10 border-violet-500/20 text-violet-100'
                : pendingSummary
                ? 'bg-emerald-500/10 border-emerald-500/20 text-emerald-300'
                : 'bg-blue-500/10 border-blue-500/20 text-blue-300'
            }`}
          >
            {transcribing && <><Loader2 size={12} className="animate-spin" /> {locale === 'en' ? 'Transcribing via Gemini...' : 'جارٍ تفريغ الصوت بواسطة Gemini...'}</>}
            {aiThinking && <><Loader2 size={12} className="animate-spin" /> {locale === 'en' ? 'Coach Pro is thinking...' : 'Coach Pro يفكر في الإجابة...'}</>}
            {!transcribing && !aiThinking && voiceError && <span>⚠️ {voiceError}</span>}
            {!transcribing && !aiThinking && !voiceError && pendingSummary && !aiReply && (
              <span className="line-clamp-2">📌 {locale === 'en' ? 'Summary ready — will be attached when sent.' : 'الملخّص جاهز وسيُرفق مع الرسالة عند الإرسال.'}</span>
            )}
            {aiReply && (
              <div className="flex-1 space-y-1">
                <div className="flex items-center justify-between">
                  <span className="font-bold flex items-center gap-1"><Bot size={12} /> Coach Pro AI</span>
                  <div className="flex items-center gap-2">
                    <button
                      onClick={() => speaking ? stopSpeaking() : speakText(aiReply.replace(/^.*?💬\s*/s, ''))}
                      title={speaking ? (locale === 'en' ? 'Stop' : 'إيقاف القراءة') : (locale === 'en' ? 'Listen' : 'استمع للرد')}
                      className="text-violet-300 hover:text-white text-[10px] flex items-center gap-1"
                    >
                      {speaking ? <Square size={10} /> : <Volume2 size={10} />}
                      {speaking ? (locale === 'en' ? 'Stop' : 'إيقاف') : (locale === 'en' ? 'Listen' : 'استمع')}
                    </button>
                    <button onClick={() => { stopSpeaking(); setAiReply(''); }} className="text-violet-300 hover:text-white text-[10px]">
                      {locale === 'en' ? 'Close' : 'إغلاق'}
                    </button>
                  </div>
                </div>
                <pre className="whitespace-pre-wrap font-sans text-[12px] leading-relaxed">{aiReply}</pre>
              </div>
            )}
          </motion.div>
        )}
      </AnimatePresence>

      {/* Smart Mic mode picker */}
      <AnimatePresence>
        {micMenuOpen && !recording && !transcribing && (
          <motion.div
            initial={{ opacity: 0, y: 8 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: 8 }}
            className="px-4 pt-3 bg-slate-800/40 border-t border-white/5"
          >
            <div className="grid grid-cols-3 gap-2">
              <button
                type="button"
                onClick={() => startWithMode('text')}
                className="flex flex-col items-center gap-1 p-3 rounded-xl bg-slate-900/60 hover:bg-blue-600/20 border border-white/5 hover:border-blue-500/40 transition-all"
              >
                <Mic size={18} className="text-blue-400" />
                <span className="text-[11px] font-bold text-white">{locale === 'en' ? 'Voice → Text' : 'صوت → نص'}</span>
                <span className="text-[9px] text-slate-500 leading-tight text-center">
                  {locale === 'en' ? 'Transcribes into input' : 'يفرّغ كلامك في خانة الكتابة'}
                </span>
              </button>
              <button
                type="button"
                onClick={() => startWithMode('note')}
                className="flex flex-col items-center gap-1 p-3 rounded-xl bg-slate-900/60 hover:bg-emerald-600/20 border border-white/5 hover:border-emerald-500/40 transition-all"
              >
                <FileAudio size={18} className="text-emerald-400" />
                <span className="text-[11px] font-bold text-white">{locale === 'en' ? 'Voice Note' : 'رسالة صوتية'}</span>
                <span className="text-[9px] text-slate-500 leading-tight text-center">
                  {locale === 'en' ? 'Sends audio + text to coach' : 'يرسل الصوت + النص للكوتش'}
                </span>
              </button>
              <button
                type="button"
                onClick={() => startWithMode('ai')}
                disabled={!currentUserProfile}
                className="flex flex-col items-center gap-1 p-3 rounded-xl bg-slate-900/60 hover:bg-violet-600/20 border border-white/5 hover:border-violet-500/40 transition-all disabled:opacity-40 disabled:cursor-not-allowed"
              >
                <Bot size={18} className="text-violet-400" />
                <span className="text-[11px] font-bold text-white">{locale === 'en' ? 'Voice → AI' : 'صوت → AI'}</span>
                <span className="text-[9px] text-slate-500 leading-tight text-center">
                  {locale === 'en' ? 'AI Coach replies instantly' : 'Coach Pro يردّ مباشرة'}
                </span>
              </button>
            </div>
          </motion.div>
        )}
      </AnimatePresence>

      {/* Input */}
      <form onSubmit={handleSendMessage} className="p-4 bg-slate-800/30 border-t border-white/5 flex gap-2">
        <input
          type="text"
          className="flex-1 bg-slate-900/50 border border-white/10 rounded-xl px-4 py-2 text-sm text-white outline-none focus:border-blue-500 transition-all"
          placeholder={
            recording
              ? locale === 'en'
                ? `Recording (${micMode === 'ai' ? 'AI question' : micMode === 'note' ? 'voice note' : 'transcript'})... tap ⏹`
                : `جارٍ التسجيل (${micMode === 'ai' ? 'سؤال للذكاء' : micMode === 'note' ? 'رسالة صوتية' : 'تفريغ نصي'})... اضغط ⏹`
              : locale === 'en' ? 'Type your message...' : 'اكتب رسالتك هنا...'
          }
          value={newMessage}
          onChange={(e) => setNewMessage(e.target.value)}
          disabled={recording || transcribing}
        />
        <button
          type="button"
          onClick={() => {
            if (recording) { stopRecording(); return; }
            if (transcribing || aiThinking) return;
            setMicMenuOpen((v) => !v);
          }}
          disabled={transcribing || aiThinking}
          title={recording ? (locale === 'en' ? 'Stop recording' : 'إيقاف التسجيل') : (locale === 'en' ? 'Smart Mic — choose mode' : 'الميكروفون الذكي — اختر الوضع')}
          className={`p-2 rounded-xl transition-all shadow-lg ${
            recording
              ? 'bg-red-600 hover:bg-red-500 text-white shadow-red-600/30 animate-pulse'
              : micMenuOpen
              ? 'bg-blue-600 text-white shadow-blue-600/30'
              : 'bg-slate-700 hover:bg-slate-600 text-slate-200'
          } disabled:opacity-50 disabled:cursor-not-allowed`}
        >
          {recording ? <Square size={18} /> : transcribing || aiThinking ? <Loader2 size={18} className="animate-spin" /> : <Mic size={18} />}
        </button>
        <button
          type="submit"
          disabled={!newMessage.trim() || recording || transcribing}
          className="p-2 bg-blue-600 hover:bg-blue-500 disabled:opacity-50 disabled:cursor-not-allowed text-white rounded-xl transition-all shadow-lg shadow-blue-600/20"
        >
          <Send size={18} />
        </button>
      </form>
    </div>
  );
}
